version: '3'
services:
  neo4j:
    image: neo4j:4.2
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    environment: 
      # Raise memory limits
      - NEO4J_AUTH=neo4j/secret
      - NEO4J_dbms_memory_pagecache_size=7G
      - NEO4J_dbms.memory.heap.initial_size=5G
      - NEO4J_dbms_memory_heap_max__size=5G
