version: "3.4"
services:
  channels:
    build:
      context: channels
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 channels/channels.py ",
      ]
    ports:
      - 5678:5678
  comments:
    build:
      context: comments
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 comments/comments.py ",
      ]
    ports:
      - 5678:5678
