version: "3.9"
services:
  channels:
    build:
      context: channels
      target: debug
    ports:
      - 5678:5678
  comments:
    build:
      context: comments
      target: debug
    ports:
      - 5678:5678
  # zookeeper:
  #   image: confluentinc/cp-zookeeper:latest
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   ports:
  #     - 22181:2181
  #   volumes:
  #     - ~/images/zoo/data:/var/lib/zookeeper/data
  #     - ~/images/zoo/log:/var/lib/zookeeper/log

  # kafka:
  #   image: confluentinc/cp-kafka:latest
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - 29092:29092
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_CREATE_TOPICS: "new_channel:1:1,new_video:1:1,new_replies:1:1"
  #   volumes:
  #     - ~/images/broker/data:/var/lib/kafka/data
