FROM python as base

RUN mkdir /service/
WORKDIR /service

COPY requirements.txt /service/requirements.txt
RUN python -m pip install --upgrade pip
RUN python -m pip install -r requirements.txt

### DEBUG ###
FROM base as debug

RUN python -m pip install debugpy

COPY ./* /service/

ENTRYPOINT [ "python", "-m", "debugpy","--wait-for-client", "--listen", "0.0.0.0:5678","channels.py" ]

### PRODUCTION ###

FROM base as production
COPY . /service/
ENTRYPOINT [ "python", "channels.py" ]
