search:
    state: false

include:
    videos: [2FJdEVaB6k0, trt9QY6TFwA]
       
videos:
    state: true
    update_frequency: 1

channel_videos:
    state: false

channels:
    state: true
    update_frequency: 1

video_comments:
    state: true
    update_frequency: 1

comments:
    state: true
    update_frequency: 14

replies:
    state: true
    update_frequency: 14