search:
  state: False
  default-limit: 400
  default-lanuages: [en]
  keywords:
    - keyword: Minecraft
      games: [Minecraft]
      languages: [en]
      limit: 400
    - keyword: League of Legends
      games: [League of Legends]
    - keyword: Valorant
      games: [Valorant]
    - keyword: Roblox
      games: [Roblox]
    - keyword: Garena Free Fire
      games: [Garena Free Fire]
    - keyword: Grand Theft Auto V
      games: [Grand Theft Auto V]
    - keyword: Fortnite
      games: [Fortnite]
    - keyword: "Animal Crossing: New Horizons"
      games: ["Animal Crossing: New Horizons"]
    - keyword: "Animal Crossing: Wild World"
      games: ["Animal Crossing: Wild World"]
    - keyword: Playerunknown's Battlegrounds
      games: [Playerunknown's Battlegrounds]
    - keyword: World of Warcraft
      games: [World of Warcraft]
    - keyword: "The Elder Scrolls V: Skyrim"
      games: ["The Elder Scrolls V: Skyrim"]
    - keyword: Mortal Kombat 11
      games: [Mortal Kombat 11]
    - keyword: Apex Legends
      games: [Apex Legends]
    - keyword: FIFA 19
      games: [FIFA 19]
videos:
  state: True
  video-ids:
   # Dream and George
   - 5z8VwyGOuXg
   - I5RhX06NYvQ
   - nQoHaT3r4tc
   - lfOakuOT5dY
   - KYkAN62IoMo
   - Sxgj9unnN6E
   - Y7t5B69G0Dw
   - bOOfg7d1b6c
   - mltj5p6l1-8
   # Techno
   - yFtLvm_cCcI
   - QKpWvPEZ5bo
   - Pw6b0-Wi_FI
   - cmkkWvDRm4k
   - lYdEY6Wit_I
   - 09CeBwGbCeg
   # PewDiePie
   - qpLFWwo7tL0
   - Wm-HtcQ48_I
   - 2U8OHYXeC3I
   - jLuMFyAL61Q
   - jAhfePpDMjo
   - WNUtEAFiDE8
   # TommyInnit
   - epLQTad1kFU
   - ohrhxTLvfds
   - 76aQGDv-O8s
   - Qua_b277fic
   - 2u8y7o6JMQY
   - erL1XmgORA0
   # Badboyhalo 
   - yzOGik0EBgs
   - nEOnqOqQ-4g
   - yTCOFoOif3U
   - vWSW_K0FjR0
   - AkYZ8_QzUOw
  games: [Minecraft]
  languages: [en]
comments:
  state: True
  video-ids: ["--ay5iFPpuk", "--pWNKkn3pw", "-1wfOFfaqd4", "-2SUBnuCPnY", "-3mzBlZWVQg", "-4Is1mtkN90", "-4nXCL-jQq0", "-6-WWLnA9U4", "-6B1I86HT34", "-7R26Ny1zF4", "-7Z1ttsQUKk", "-7dgL1XqM8Q", "-A5yAILtwBs", "-ACE37K3r8k", "-AFCuefA71U", "-Amoc8Jymxc", "-AmsE6HM_fs", "-Cu43NlCVxc", "-CzPu3ZnpBA", "-Dbne2TgCWg", "-Exj7ch8P3M", "-Fs_eXGeRzw", "-GEKdiR0lWo", "-GKrL6lSpBU", "-GQPCLyxmm0", "-HVx5Yhlpzk", "-Hh95fSQRiE", "-HijCGlbl4M", "-I-5Vz-p1fA", "-I2CgCJjc_8", "-I_Xvc8vGgM", "-JbRaBs5n-0", "-KLrD7Mdknc", "-KqQLS990uc", "-M2Fr-YPtiY", "-MThpEvpxDY", "-M_r8MKQ3mo", "-Me0qsYV72A", "-N8dcRlePi8", "-NeluHCd8Ls", "-NhevGw_qBw", "-O9Fcg1-2gE", "-OlESzMpxmo", "-P8l2r9DSx8", "-PApf4NrnNA", "-QEzfMXc3hw", "-Qp2k9qIunQ", "-RsuUaNq3oM", "-SGww8ANly8", "-SHGRv70w8Q", "-SY8MaekxWg", "-TtG9XVS-Gk", "-UKKFGSMVIU", "-VFTp2oTlDQ", "-Wli4FOWwhs", "-Z4lj05F6ak", "-aigas1-oFc", "-axBNo2hkic", "-bfMcmBWfmg", "-e0sgMFxals", "-eMY9FsNjrk", "-eYuIqEMNJI", "-fWL6CantFw", "-gIxO8fiPxY", "-gksrhAtPBA", "-hKGN0IXxTE", "-hNkP8ZhMUM", "-hOY1GL7RFY", "-hVijDMBfSY", "-i3ZJZkX-Ds", "-iMe0TIBDLM", "-ia5CQqa7Ks", "-j9VRQ0tNn4", "-jPHpTDwy4k", "-jav_hG8h-I", "-kagngwNw1o", "-kjD-1eieQc", "-lZP2etsPCM", "-mUj28cNLdM", "-mZbYyyzrns", "-ovHC768rC0", "-pYoWYO-y9Y", "-pjh7pGCmCs", "-q0p8M1SLLY", "-rMXpIN922g", "-rXay03Xp9U", "-sUc89J1dVA", "-si0Z34g6j0", "-ugN78Qlw1c", "-vJjp8R124k", "-vSBIIJih-w", "-vksjUn4EbA", "-w9a3RZHwQE", "-wAbbt0MgLc", "-wEazjIukF0", "-wPg1tNEWmo", "-ylVnuPWlJM", "-yniMUdqMhk", "-zmjtjgQYe8", "0-L1hP5IaBo", "0-UYJnOWNUM", "02DBDiLEPSs", "02DIVSnLWT4", "02L87GdA7Zc", "02txn0H6pVY", "03RZxsgk4Bc", "03rpuXqiw5M", "03uQ-LW5caA", "04NoIDM05f0", "04miPCu4Bls", "05CRPk_F3gI", "05H54wxwG2I", "05Nqxcj1pAs", "06OPARYU-YE", "06OgBMSRiPg", "06cJmcfI850", "06hMEXZrlSU", "08267yO1tZw", "08BZ5CbHGyo", "08LE0HdzRdk", "08QBBaK4X3M", "08ud13VdQRo", "09FhamQVc-U", "09xk0LeRb8M", "0A7cW56HIKU", "0Ayo_i6Eu68", "0BQFnGEN1ec", "0C4wSyVNlNQ", "0C8fpAWJbO8", "0DCc8D-W86I", "0DUuT0gA-SE", "0EE6qXkz39w", "0EKx6xXeFf8", "0Eqy75JA-wU", "0GxSgk4uWeU", "0Hs_2vEEiBM", "0IPYovqfqiA", "0IRwQP7nOq8", "0JNfBIHqBuY", "0KO1CPWglTU", "0KfQYHtbtyA", "0L_xB5UKkpM", "0NGw4zEhwqc", "0NzJZ-YKfuE", "0O9mtZkLFBc", "0OqTJR-0vuE", "0PGFVbz723A", "0PJj-aTMbhg", "0PmEVxHnthI", "0QRTAwJoXuk", "0QZiLyzPoJ0", "0QqI4o4aDnY", "0RmuEhRQ-1s", "0V4taif__mo", "0Wjvzdl8XS4", "0WlHLMUrDXI", "0WvLjlknmJ4", "0X4lQhWeNyI", "0XacgCuILzE", "0XtAavLEdMk", "0_4BhkS34cs", "0_QJU4JmM9M", "0alI2yR3Be4", "0dR-kH2G33Y", "0dqb91cFlTU", "0dydN4V7Rko", "0ecJgufa9PQ", "0fz3dhQhZ40", "0gKo2_7lv04", "0giRCGA6FDk", "0hIxvhLnAhA", "0hb2bzqqQIE", "0iEqQbPFr-M", "0j6Fgg4uQxE", "0jSpnsOQPiU", "0jWetqSVGNc", "0jYcT-U_BiI", "0jhxLES7JcE", "0jrkmjfiaIg", "0l9aS3hoV2M", "0lLd22QwJXY", "0maWbr0FHKY", "0n4pa6cFvl0", "0nHQJp9jscc", "0o9KP8FHOnw", "0qSY6bNImQA", "0rN1eQ-BMNo", "0rgPoE4lVpg", "0tMMvHKC2Cs", "0t_lFcBE_wQ", "0uyLRPmmYPk", "0xEvmoIaq_4", "0zBV9CxlGL4", "0zjAY7nnocw", "1-hl29zg-FE", "1-xE2l-6jMk", "10vuK64nOcA", "11HoR7_9NyE", "120OBXKb7-o", "12PLeURwnvs", "12TYTVXk6CI", "12oT2Kg8Tk8", "12yFCkfOv6I", "13ep1XrkBbY", "13tywawB2pY", "14vlJuCYFBA", "14xj4ohhvaE", "1528SfzcG4g", "18WWx0x8v4s", "19ORoTGo2Hk", "19tXeHJns1E", "19zrFCkYcxY", "1EU_aO0Iuyw", "1EusAgXKSu4", "1FZbDuqoax8", "1FsxBCmrnuY", "1GEk7mySsQs", "1GOFBjDlHjw", "1GTP4qNZ0WE", "1Hd1EVEqsNo", "1IR6ArFaQFc", "1JRR94DPGsM", "1J_v711KAYA", "1JxL7qaDk9w", "1LwDMwt8U-s", "1MyDvkbW9Lk", "1OIemEZOG8s", "1Q0lspXUOXA", "1QqusKQUe7o", "1R4-bIENw3Y", "1SReU9XWNN0", "1TBM7n2WmaI", "1TRv5wTl1-w", "1TbXuJa7APU", "1UmrMPHFI8w", "1UycS2VdoMk", "1VH0L8FPrJs", "1V_T2EGpXO0", "1XGHw0uCVDo", "1XL_kRFxZ5o", "1XXcrpeI-lE", "1XuXN0pQF-0", "1Ypjr1ZWies", "1Z-ozap0S_Q", "1ZVbtW1I1rw", "1_R_g4O1TNU", "1__cddSAEOs", "1__i51ypHJI", "1asPju5yZCo", "1b5r2Rk_iEQ", "1c2Xs3IRXI4", "1d_Dd3O4yfk", "1emZhgmIkac", "1ffMizWYyHg", "1gPvhlsTcwg", "1gl2L2rWmag", "1hH0XeMO3pk", "1hLJE_Enf7g", "1i0iaPjLFTc", "1iIkSUWo0aU", "1j-JeR7fVGw", "1jDSJjHlkas", "1jQYObKTIG8", "1kG7yr049Ns", "1nDjywX6d20", "1pbM-sLBHhA", "1q1jTTDn65s", "1qkPSTCvqXU", "1rOFcfR4HfM", "1r_8XGe35TA", "1sGqYg6f9uw", "1stKQkIwYQY", "1swismLE_5g", "1tW2S1AdZos", "1tiRAK9lK6Y", "1tr7x30cs_k", "1uOE3Uj0sWc", "1vCyEKoSvoU", "1vbX0e4FH7A", "1w45r_HQPr4", "1xE99STU3-M", "1xGcjuq5xrw", "1xZdNUiQczw", "1yzNNVqJwd4", "1zEPj3owp08", "1zaeGqHGLqg", "2-KrLlkoEHo", "208aBSw-usc", "20jH_7tlKUw", "21lSKsklLMc", "23MXSjqS5mE", "23qLyHguqcQ", "24CaIVaOvIg", "257W5N1O8C8", "25AMPsD7HGA", "25oQxfGHo9c", "266WPqnB-yg", "26p1n-cXzKQ", "27WI1Ig_RO8", "27w3PRxuaXQ", "28DXwnTfTKI", "28y8Uv3BLp8", "29BCxvGLl3A", "29CuCG2jER8", "29SyvG23UOs", "29ZW_e4Yppw", "29jO9nXLHBY", "29jetbZjp1s", "29kez5LzZAY", "29t06nyGnZw", "2AbdE_KIeDA", "2B49serq5Ts", "2Baf-Qoxtxg", "2BaqhSxMW3o", "2BmiOr7Sr9E", "2Bn2j6LQepk", "2CGDmIAkSMM", "2DvIOQB30xc", "2EfGXMe9f4w", "2EyRzJdphMg", "2FE7nkYrNA0", "2HqzpswU3po", "2I9t4OkUmI0", "2K2nwXlAsBc", "2LzUGPIyqW0", "2MAKgXWHTeY", "2MjM1X7FbZ4", "2N-_ut68s6I", "2N0RDgaNNcs", "2PPz6Xkrjgk", "2Q2Fma3YF6E", "2QyX-MX3p1A", "2RM8IwSB__c", "2RpIJdWDsqI", "2Td-ixCywSE", "2UIA4LcozSU", "2Vg0nizTwXg", "2WH2kxEk1uE", "2XOF8tlDRP0", "2XqjlcuYR58", "2YyzbXecUgQ", "2ZB73-XpxR0", "2ZRqL-Sjj-Y", "2ZUKANfSvYw", "2ZYvJjKBVR8", "2ZqYs9B6T0c", "2Zy9fs8dfOM", "2aH6LMYB4AQ", "2ayZmclKDIY", "2cYqKJc_bV8", "2cauhCUBbZU", "2d9jjP3XnTk", "2exwA-HQ-Uw", "2fQomFfATWA", "2fRk5AfQs5A", "2fbGlH2C1WI", "2fe864PP2s4", "2fjVd_kwG4I", "2g2Xr3CsesM", "2gwM5PqivCc", "2h5i2fCaGzo", "2h5kTU3LlxE", "2iJDFJGs1Hg", "2jMmBh-Rjic", "2jOOBKWDE7E", "2jmyZe-YSpw", "2jw8clt_LPM", "2koQxonudIw", "2kq9UOOJ6qg", "2l9XsoyV-Tc", "2mu1LdTgsGA", "2n1mR40XIJw", "2nAQlezLqxA", "2nN9Q9h-bXk", "2ntrw94Pbe0", "2pSbVFsTGds", "2q-95c-pQSM", "2tEsn5sHEcc", "2tFNCc4zgS4", "2tvlUzf9XKc", "2txMs-pF-5g", "2vatP0EJQCk", "2yLLy8lLgTU", "2yoizlBZ_YY", "2z2orou_220", "2zRdGraXT0U", "2zSaRu3LE04", "3-0GaznTZT4", "3-Zr8w8WIgs", "30Wifx5MAE0", "30YrgmF_-PM", "30tzHXqhvvc", "31tL33YqkbU", "32AFOE0mmeM", "33FVzjN7yy4", "33XNnmZyz7Q", "34w2vF77oaI", "35ctbFmFUqU", "35pTrYQ6CJU", "366nwB2Kaao", "36dUZ5FEptk", "36glFr0eXFc", "37xHIC5gvYM", "39wJoK8wZtI", "3A1Fup7J3AE", "3AXxhsg_iZ0", "3BdVvXBkSs4", "3CdfqaZ_Etk", "3CycRKQJ0tA", "3DMWqriE2a0", "3E-GrvMLr1o", "3E7njICE_TM", "3FIXstWx5MY", "3FhRp8o12Ro", "3GGEXN-9lBg", "3H0vVds1oG4", "3H_0JONtZiQ", "3IOi9MXPMVg", "3Jc_FdpgYVc", "3KcmQZF-ZRY", "3LCkusAx-i4", "3Lav9SPEyxA", "3Lsq4L2s9YI", "3LvSzItAom4", "3M5XKIj8644", "3MVoh-_HoKs", "3McYAk1RfTc", "3MyHggB0ZEc", "3OTNU3uMv9k", "3OV8EQQ8xIc", "3OxXWjH_Ci4", "3PjBSicSVqI", "3PpMh7UeadY", "3QOvlHeQ0EE", "3Qfun100KSo", "3Qn2Xf2vSEM", "3R4ZFia_7H4", "3TprnGVwyog", "3UaG0u1i3Do", "3UfgZgwjpOc", "3Up7NdZwQqA", "3V2nOIDirIY", "3VRP51xAD_U", "3VTQe3BXjeo", "3XUA7qzcraQ", "3Y8Nbuapfx0", "3Ylfr2OXqsw", "3Z4HFf4BKbw", "3ZKx-VolcBo", "3aXB3Dbxtng", "3aZucFLPihw", "3abwgiykmMg", "3dAcxdfcNiQ", "3dxQyIkJP8g", "3eJNU0wdzrM", "3eiHE2pX8uY", "3glbgEXveZE", "3h_e4hQCcQg", "3hkjFVED6-M", "3hsL1vZPSLg", "3i6PR5ksFsU", "3i81-LjVf5g", "3i_FIlQOp6k", "3j5rZFPx_Zk", "3jz7CbFmDbA", "3kXIuNXLXFs", "3kwKhyWRRds", "3lR-gimPWvo", "3m0KLu6hdi0", "3nULDAzXMGI", "3oRQUrggnDk", "3p8jLMz0lu8", "3qpzExqOKdo", "3rLYsCCwnwE", "3sR690UQpEo", "3tbXYuazLik", "3twZIbCrua8", "3u_ZrbTdyNg", "3vhphi9yEj8", "3xl9qH0SvG4", "3z3dOSbUEiM", "3zhUeelgqFM", "4-pqb3xJY7E", "40pnmkZDSFE", "41DTuqWxUrk", "42jW4UIPBa8", "434EuGhwg5M", "43XsLyjaIQg", "43ZMY-sK8P8", "43i1V8pZ-Wo", "43pY95So1g0", "443FYE7zhbE", "447s_106HtU", "447yCGjhBCc", "44T6XzYiHJE", "461G6CjB8y0", "47r4Ja_uwJg", "48ACZ3V7e74", "4B1ylA7bhRo"]
  channel-ids: []
    # - UCA2tt9GSU2sl8rAqjlLR3mQ # GeorgeNotFound
    # - UCTkXRDQl0luXxVQrRQvWS6w # Dream
    # - UCFAiFyGs6oDiF1Nf-rRJpZA # Technoblade
    # - UC-lHJZR3Gqxm24_Vd_AJ5Yw # PewDiePie
    # - UC5p_l5ZeB_wGjO_yDXwiqvw # TommyInnit
    # - UC0lkCn7D--uMrtwAXRj_cdw # BadBoyHalo
  all: False
replies:
  state: False
  inherit: True
  min-replies: 3
sentiment:
  state: False
  inherit: True
channels:
  state: False
  channel-ids: []
  all: False